modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="CC0"
issueTrackerURL="https://github.com/birsy/Fog-Looks-Good-Now/issues"

[[mods]]
modId="foglooksgoodnow"
version="2.0.0"
displayName="Fog Looks Good Now"
logoFile="icon.png"
authors="CAPPIN"

description='''makes fog look good by setting the fog start point to zero. additionally, adds customization to many fog features'''
[[dependencies.foglooksgoodnow]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="CLIENT"
[[dependencies.foglooksgoodnow]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="CLIENT"
